### ISSUE TITLE
Pagefront is not uploading assets when fingerprinting is disabled

### ISSUE THREAD

**Issue by rmachielse** [pagefront/ember-cli-deploy-pagefront#2]
Hi guys,

First, your hosting tool is amazing! It looks very nice!

Unfortunately, while I am setting up the integration with ember-cli-deploy, I run into an issue.
Pagefront doesn't seem to work properly when fingerprinting has been disabled. It keeps saying "Uploaded 0 assets" although I edited multiple files.

Would it be possible/necessary to turn off the incremental deployment in this case?

Thanks!

**Comment by jasonkriss** [comment]
Hey @rmachielse. Thanks for the kind words! Do you mind explaining a lil bit why you are disabling fingerprinting. Currently, there is no way to turn off incremenatal deploys as this isn't a use case we had really considered.

**Comment by rmachielse** [comment]
Hi @jasonkriss, no problem!

I disabled fingerprinting because on deploy, I deploy the website to you in that case, but I also build a chrome app. Currently that doesn't support fingerprinting so I disabled it. Off course fingerprinting is preferred so I might want to fix that. Still I think there are some limitations in that case, since there are files that aren't fingerprinted that need to be updated as well. For example, I have a `manifest.appcache` file as well that is not being fingerprinted. Off course I could build something to fingerprint that too manually but I think it would be more desirable if pagefront can handle it without fingerprinting as well. Ideally it can recognize for each file if it has been fingerprinted and upload it if it has either not been uploaded or not been fingerprinted. That would still save the biggest delay of uploading images and stuff. Is the homepage being uploaded every time? Thanks!

**Comment by jasonkriss** [comment]
Thanks a lot for the description @rmachielse. That's super helpful. While the chrome app is a lil outside the Pagefront happy path, you bring up a great point... "Ideally it can recognize for each file if it has been fingerprinted and upload it if it has either not been uploaded or not been fingerprinted." I think that's the correct way to do it.

We are working hard to push out multi environment support so we'll make this change as soon as the environemnt stuff is done. I'll ping you to let you know when it's ready. Thanks again!

**Comment by rmachielse** [comment]
I totally understand! Thank you for taking this up!

**Comment by jasonkriss** [comment]
@rmachielse I was able to get this taken care of pretty quick. Just deployed the change so it shouold be working now if you try deploying again. Let me know if you have any more issues though. Thanks!

**Comment by rmachielse** [comment]
Thank you for fixing it this quick! It is indeed uploading all 35 assets now. However, if I refresh my site on pagefront it looks like it hasn't been refreshed. If I look at the source the files haven't been updated. Is there a delay until assets have been updated?

**Comment by jasonkriss** [comment]
Can you update to the latest ember-pagefront: `npm install --save-dev ember-pagefront@0.9.7` and then deploy again. Then try doing a hard refresh in the browser. Once you do that, let me know if you still aren't seeing the new assets. Thanks for your patience on this @rmachielse!

**Comment by rmachielse** [comment]
Hi @jasonkriss, thanks for diving in it again! I have upgraded `ember-pagefront` and it uploads all files. But still, If I look at the files, they remain the old ones, even when I use curl. For example my `manifest.appcache` file (http://bit.ly/1jxxymw). According to my local `tmp/deploy-dist` dir, the second line of that file should be:

```
# version ae175acad1d10ecf3fd69afc882747a5
```

While if I look at the file behind the url it's still:

```
# created 2015-11-29T23:09:40.836Z
```

I hope you can find something. Thanks!

**Comment by jasonkriss** [comment]
@rmachielse Thanks for your patience on this. We will get it figure out! I'll get back to you soon.

**Comment by jasonkriss** [comment]
@rmachielse Let's take this offlien if you don't mind. I just sent you an email. Thanks!
