### ISSUE TITLE
Support non gzipped-files as well

### ISSUE THREAD

**Issue by rmachielse** [pagefront/ember-cli-deploy-pagefront#5]
Hi @jasonkriss 

I am currently running into an issue where a file is added to the distFiles after gzip has been run.
This causes the file to be uploaded to pagefront with the gzip encoding header, while the file isn't actually being gzipped. This leads to strange decoding errors.

Would it be possible to only set the gzip header when the file has actually been gzipped? I think you can use the `gzippedFiles` variable that ember-cli-deploy-gzip returns for that.

**Comment by jasonkriss** [comment]
Hey @rmachielse, thanks for bring this up and putting a PR together as well! The PR looks very reasonable. Can I ask how a file is being added to distFiles after gzipping has happened? Just wanna make sure I have full context before merging it in.

**Comment by rmachielse** [comment]
@jasonkriss awesome! I believe the ember-cli-deploy-gzip addon takes the distFiles array from ember-cli-deploy-build and gzips every file in it that matches the filePattern. I think it doesn't change distFiles, but it adds a gzippedFiles array to the context, so any addons after that know what files have been gzipped. In my case another addon adds an extra file to distFiles, after gzipping has already been done, so it won't be gzipped.
